pjhampton/Gramophone

- formats/format-quote.php
- static/css/app.css
Added css and html for quote format
> Blockquote & Cite

- formats/format-image.php
- static/css/app.css
> Added post_format_image

- .editorconfig
This pull request adds a .editorconfig file. #33
> Add a editorconfig file #33

- config/pagination.php
Check it before merge it, I think now is working. #36
> Fixed pagination

- functions.php
References: #38 Hope it suits the needs that you requested :)
> Added bootstrap styling for Password Protected form, references: #38

- static/css/app.css
Added the requested background-color! :octocat:
> Add #FFEBCD to .sticky class

- static/css/app.css
Changed the horizontal padding of the articles to match the vertical padding.
> Added horizontal padding to articles 

- formats/format-aside.php
- static/css/app.css
> Aside format styling

- formats/format-aside.php
I made a little (non-crucial) typo, but in my opinion it is more neat to fix it.
> Fix little typo

- formats/format-link.php
- static/css/app.css
> Added post_format_link

- formats/format-gallery.php
- static/css/app.css
> Gallery format style

- config/woocommerce.php
- page.php
- woocommerce/cart/cart-totals.php
- woocommerce/cart/cart.php
- woocommerce/cart/cross-sells.php
- woocommerce/checkout/form-checkout.php
- woocommerce/checkout/payment-method.php
- woocommerce/checkout/payment.php
- woocommerce/checkout/review-order.php
- woocommerce/checkout/thankyou.php
- woocommerce/order/order-details-customer.php
- woocommerce/order/order-details.php
Add style to cart, checkout and order details using Bootstrap 4
> Basic styling for WooCommerce checkout

- config/styling.php
- functions.php
> Moving div_wrapper function to config/styling.php file

- config/styling.php
- config/widgets.php
- static/js/app.js
I have done all the widgets that you mentioned and that make sense
I did the search widget (as I said I actually made it work for all search forms using the default wordpress form from get_search_form())
Archives, Recent Posts, Recent Comments and Categories as well as any widget using lists have also been done. I did archives using a filter in the code where the list is pulled and the rest is done via javascript in app.js - it seemed excessive ripping out and overriding the class when js could simply insert the classes.
I hope you like it.
> All widgets done

- config/admin.php
Fixes: #77 
Made the code I added match the rest of the code.
> Cleaned up code for two functions added.

- comments.php
- functions.php
- includes/comments.php
See ticket #80 for reference.
Fixes: #80
> Styling comments

- config/enqueue.php
- home.php
- static/css/app.css
- static/js/app.js
- static/js/js.cookie.js
> Remember display selection

- .gitignore
- home.php
Fixes #88
**Changes**
- If featured image is present then use it
- If not present then default to the existing image
**Screenshot**
> Add featured thumbnail in grid view

- .github/CONTRIBUTING.md
> Removed Import the WooCommerce dummy data line in CONTRIBUTING.MD

- home.php
It outputs Page 1 in front page and page X in subsequent pages.
Also one thing I noticed is this file won't be shown if a front-page.php is present (which is) so it can be removed to see this one as front page.
Fixes #94
> Fixed home.php pagination issue

- eject.sh
> If you are renaming the file don't forget to rename it in the script

- functions.php
Closes #92.
While this doesn't change specifically for the Post Gallery format, it does apply Bootstrap 4 Grid and Image styles for the post gallery shortcode output, which is expected for the Post Gallery format.
> Add Bootstrap 4 styling for gallery

- static/css/app.css
Forces image expand to full-width of viewport.
References Issue #106
> Adds full-width styles to featured images on mobile

- docker-compose.yml
> Fix indentation

- formats/format-video.php
- static/css/app.css
I also removed some video css classes as they were not used. Found that they were created 2 years ago together with one function, which used them and now is long gone.
> Update video classes

- 404.php
- header-nonnav.php
- static/css/app.css
Tries to solve #115 
Fixes: #115
> Better 404 page

- static/css/app.css
> Make images alligned in gallery
